[workspace]

members = [
    "necsim/core",
    "necsim/core/bond",

    "necsim/impls/no-std",
    "necsim/impls/std",
    "necsim/impls/cuda",

    "necsim/plugins/core",
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/metacommunity",
    "necsim/plugins/statistics",
    "necsim/plugins/species",
    "necsim/plugins/demo",

    "necsim/partitioning/core",
    "necsim/partitioning/monolithic",
    "necsim/partitioning/mpi",

    "rustcoalescence",

    "rustcoalescence/scenarios",

    "rustcoalescence/algorithms",
    "rustcoalescence/algorithms/monolithic",
    "rustcoalescence/algorithms/independent",
    "rustcoalescence/algorithms/cuda",
    "rustcoalescence/algorithms/cuda/kernel",
    "rustcoalescence/algorithms/cuda/kernel/specialiser",
    "rustcoalescence/algorithms/cuda/kernel/ptx-jit",

    "rust-cuda",
    "rust-cuda/rust-cuda-derive",

    "third-party/array2d-no-std",
    "third-party/contracts",
    "third-party/float-next-after-no-std",
    "third-party/ron",
    "third-party/rust-ptx-builder",
    "third-party/RustaCUDA",
    "third-party/RustaCUDA/rustacuda_core",
    "third-party/RustaCUDA/rustacuda_derive",
]

default-members = [
    "rustcoalescence",
    
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/metacommunity",
    "necsim/plugins/statistics",
    "necsim/plugins/species",
    "necsim/plugins/demo",
]

[profile.release]
opt-level = 3
lto = "fat"
